name: Repository Hygiene

on: pull_request

concurrency:
  group: pr-repo-hygiene-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  superlinter:
    name: Lint bash, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_MD: true
          VALIDATE_YAML: true

  refresh-website-content:
    name: Verify refresh-website-content script runs successfully
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Run refresh-website-content.sh
        run: .ci-scripts/refresh-website-content.sh
